const { createClient } = window.supabase;
const sb = createClient(INVENTORY_CONFIG.supabaseUrl, INVENTORY_CONFIG.supabaseKey);

const state = { view: 'overview', items: [], categories: [], movements: [], session: null };
const $ = (s) => document.querySelector(s);
const esc = (v='') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const statusLabel = s => ({SUFFICIENT:'Suficiente',LOW:'Stock bajo',CRITICAL:'Reponer'}[s] || s);
const statusClass = s => ({SUFFICIENT:'ok',LOW:'low',CRITICAL:'critical'}[s] || 'ok');
const fmt = n => Number(n || 0).toLocaleString('es-PE',{maximumFractionDigits:3});

async function init(){
  const {data:{session}} = await sb.auth.getSession();
  state.session=session;
  if(!session){ renderLogin(); return; }
  await loadData();
  render();
  sb.auth.onAuthStateChange((_e,s)=>{state.session=s;if(!s) renderLogin();});
}

function renderLogin(){
  document.body.innerHTML = `<div class="login-shell"><div class="login-card"><img src="assets/quimflux-logo.png" alt="QUIMFLUX" class="login-logo"><div class="eyebrow">GESTIÓN DE INVENTARIO</div><h1>Bienvenido</h1><p class="login-sub">Accede al inventario QUIMFLUX para consultar existencias y registrar movimientos.</p><form id="login-form"><div class="field"><label>Correo electrónico</label><input class="form-control" id="email" type="email" required placeholder="correo@empresa.com"></div><div class="field"><label>Contraseña</label><input class="form-control" id="password" type="password" required placeholder="••••••••"></div><button class="btn btn-primary" style="width:100%;margin-top:8px">Ingresar</button></form><div id="login-msg" class="login-msg"></div><button id="signup" class="text-btn">Crear una cuenta</button></div></div>`;
  $('#login-form').addEventListener('submit', login);
  $('#signup').addEventListener('click', signup);
}
async function login(e){e.preventDefault(); const email=$('#email').value.trim(), password=$('#password').value; const {error}=await sb.auth.signInWithPassword({email,password}); if(error) $('#login-msg').textContent=error.message; else init();}
async function signup(){const email=$('#email').value.trim(), password=$('#password').value;if(!email||password.length<6){$('#login-msg').textContent='Ingresa un correo y una contraseña de al menos 6 caracteres.';return;}const {error}=await sb.auth.signUp({email,password});$('#login-msg').textContent=error?error.message:'Cuenta creada. Revisa tu correo si Supabase solicita confirmación.';}

async function loadData(){
  const [c,i,m] = await Promise.all([
    sb.from('categories').select('*').eq('active',true).order('name'),
    sb.from('inventory_overview').select('*').eq('active',true).order('name'),
    sb.from('movements').select('*, items(code,name)').order('movement_date',{ascending:false}).limit(200)
  ]);
  if(c.error||i.error||m.error){toast((c.error||i.error||m.error).message,true);return;}
  state.categories=c.data||[];state.items=i.data||[];state.movements=m.data||[];
}

function render(){
  document.body.innerHTML = `<div id="app"><aside class="sidebar"><div class="brand"><img src="assets/quimflux-logo.png" alt="QUIMFLUX"><div><strong>INVENTARIO</strong><span>Control de existencias</span></div></div><nav id="nav"><button class="nav-item active" data-view="overview">▦ <span>Vista general</span></button><button class="nav-item" data-view="entries">＋ <span>Entradas</span></button><button class="nav-item" data-view="exits">− <span>Salidas</span></button><button class="nav-item" data-view="alerts">⚠ <span>Reposición</span></button><button class="nav-item" data-view="movements">↕ <span>Movimientos</span></button></nav><div class="sidebar-footer"><span class="status-dot"></span> Sistema conectado<br><button id="logout" class="text-btn" style="margin-top:10px">Cerrar sesión</button></div></aside><main class="main"><header class="topbar"><div><p class="eyebrow">GESTIÓN DE INVENTARIO</p><h1 id="page-title">Vista general</h1></div><button class="mobile-menu" id="mobile-menu">☰</button><div class="top-actions"><button class="icon-btn" id="refresh">↻</button><div class="user-pill"><span>${esc((state.session?.user?.email||'A')[0].toUpperCase())}</span><div><b>${esc(state.session?.user?.email||'Administrador')}</b><small>QUIMFLUX</small></div></div></div></header><section id="content" class="content"></section></main></div><div id="modal" class="modal hidden"><div class="modal-card"><button class="close" id="close-modal">×</button><div id="modal-content"></div></div></div><div id="toast" class="toast"></div>`;
  bindShell(); renderView();
}
function bindShell(){
  $('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;state.view=b.dataset.view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$('#page-title').textContent={overview:'Vista general',entries:'Entradas',exits:'Salidas',alerts:'Reposición',movements:'Movimientos'}[state.view];renderView();$('.sidebar')?.classList.remove('open');});
  $('#refresh').onclick=async()=>{await loadData();renderView();toast('Inventario actualizado');};
  $('#logout').onclick=()=>sb.auth.signOut(); $('#mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open'); $('#close-modal').onclick=closeModal;
}
function renderView(){if(state.view==='overview') renderOverview(); if(state.view==='entries') renderMovementForm('ENTRY'); if(state.view==='exits') renderMovementForm('EXIT'); if(state.view==='alerts') renderAlerts(); if(state.view==='movements') renderMovements();}

function renderOverview(){
  const total=state.items.length, units=state.items.reduce((a,i)=>a+Number(i.current_stock),0), low=state.items.filter(i=>i.stock_status==='LOW').length, crit=state.items.filter(i=>i.stock_status==='CRITICAL').length;
  $('#content').innerHTML=`<div class="cards"><div class="card"><div class="label">Artículos activos</div><div class="value">${total}</div><div class="sub">Catálogo actual</div></div><div class="card"><div class="label">Unidades en stock</div><div class="value">${fmt(units)}</div><div class="sub">Existencia total</div></div><div class="card"><div class="label">Stock bajo</div><div class="value warning">${low}</div><div class="sub">Por debajo del mínimo</div></div><div class="card"><div class="label">Reponer</div><div class="value danger">${crit}</div><div class="sub">Sin stock o crítico</div></div></div><div class="toolbar"><div class="search"><input id="search" placeholder="Buscar por código, nombre o descripción..."></div><select id="cat-filter" class="control"><option value="">Todas las categorías</option>${state.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select><select id="status-filter" class="control"><option value="">Todos los estados</option><option value="SUFFICIENT">Suficiente</option><option value="LOW">Stock bajo</option><option value="CRITICAL">Reponer</option></select><button class="btn btn-primary" id="new-item">＋ Nuevo artículo</button></div><div class="panel"><div class="panel-head"><h2>Inventario general</h2><span class="sub" id="result-count"></span></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>Categoría</th><th>Bien</th><th>Unidad</th><th>Stock</th><th>Mínimo</th><th>Estado</th></tr></thead><tbody id="inventory-body"></tbody></table></div></div>`;
  const paint=()=>{const q=$('#search').value.toLowerCase(),cat=$('#cat-filter').value,st=$('#status-filter').value;const rows=state.items.filter(i=>(!q||`${i.code} ${i.name} ${i.description||''}`.toLowerCase().includes(q))&&(!cat||i.category_id===cat)&&(!st||i.stock_status===st));$('#result-count').textContent=`${rows.length} artículo${rows.length!==1?'s':''}`;$('#inventory-body').innerHTML=rows.length?rows.map(i=>`<tr><td><b>${esc(i.code)}</b></td><td>${esc(i.category_name)}</td><td>${esc(i.name)}<div class="sub">${esc(i.description||'')}</div></td><td>${esc(i.unit)}</td><td><b>${fmt(i.current_stock)}</b></td><td>${fmt(i.minimum_stock)}</td><td><span class="badge ${statusClass(i.stock_status)}">${statusLabel(i.stock_status)}</span></td></tr>`).join(''):`<tr><td colspan="7"><div class="empty"><strong>No hay resultados</strong>Ajusta los filtros o crea un artículo nuevo.</div></td></tr>`};
  ['search','cat-filter','status-filter'].forEach(id=>$('#'+id).addEventListener('input',paint));paint();$('#new-item').onclick=showNewItem;
}

function showNewItem(){
  $('#modal-content').innerHTML=`<h2>Nuevo artículo</h2><p class="modal-sub">Crea el bien y define su stock mínimo.</p><form id="item-form"><div class="form-grid"><div class="field"><label>Código *</label><input class="form-control" name="code" required placeholder="MAT-001"></div><div class="field"><label>Categoría *</label><select class="form-control" name="category_id" required>${state.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Nombre *</label><input class="form-control" name="name" required placeholder="Nombre del bien"></div><div class="field"><label>Unidad</label><input class="form-control" name="unit" value="UND"></div><div class="field"><label>Stock inicial</label><input class="form-control" name="initial_stock" type="number" min="0" step="0.001" value="0"></div><div class="field"><label>Stock mínimo</label><input class="form-control" name="minimum_stock" type="number" min="0" step="0.001" value="0"></div><div class="field full"><label>Descripción</label><textarea class="form-control" name="description" rows="3"></textarea></div></div><div class="form-actions"><button type="button" class="btn btn-secondary" id="cancel-item">Cancelar</button><button class="btn btn-primary">Guardar artículo</button></div></form>`;openModal();$('#cancel-item').onclick=closeModal;$('#item-form').onsubmit=createItem;
}
async function createItem(e){e.preventDefault();const f=new FormData(e.target);const initial=Number(f.get('initial_stock')||0);const {data,error}=await sb.from('items').insert({code:f.get('code').trim().toUpperCase(),category_id:f.get('category_id'),name:f.get('name').trim(),description:f.get('description'),unit:f.get('unit').trim().toUpperCase()||'UND',current_stock:initial,minimum_stock:Number(f.get('minimum_stock')||0)}).select().single();if(error){toast(error.message,true);return;}if(initial>0){const {error:me}=await sb.from('movements').insert({item_id:data.id,movement_type:'ENTRY',quantity:initial,notes:'Stock inicial'});if(me){toast(me.message,true);return;}}closeModal();await loadData();renderView();toast('Artículo creado correctamente');}

function renderMovementForm(type){const entry=type==='ENTRY';const title=entry?'Registrar entrada':'Registrar salida';$('#content').innerHTML=`<div class="panel"><div class="panel-head"><div><h2>${title}</h2><div class="sub">${entry?'El stock se sumará automáticamente al inventario.':'El stock se descontará automáticamente. El sistema bloqueará cantidades superiores al stock disponible.'}</div></div></div><form id="movement-form"><div class="form-grid"><div class="field full"><label>Artículo *</label><select class="form-control" name="item_id" required><option value="">Selecciona un artículo...</option>${state.items.map(i=>`<option value="${esc(i.id)}">${esc(i.code)} — ${esc(i.name)} | stock ${fmt(i.current_stock)} ${esc(i.unit)}</option>`).join('')}</select></div><div class="field"><label>Cantidad *</label><input class="form-control" name="quantity" type="number" min="0.001" step="0.001" required></div><div class="field"><label>Fecha</label><input class="form-control" name="movement_date" type="datetime-local" value="${new Date().toISOString().slice(0,16)}"></div>${entry?`<div class="field"><label>Proveedor</label><input class="form-control" name="supplier"></div><div class="field"><label>Documento</label><input class="form-control" name="document_number" placeholder="Factura / guía / OC"></div>`:`<div class="field"><label>Destino</label><input class="form-control" name="destination" placeholder="Área / proyecto / persona"></div><div class="field"><label>Responsable</label><input class="form-control" name="responsible"></div>`}<div class="field full"><label>Observación</label><textarea class="form-control" name="notes" rows="3"></textarea></div></div><div class="form-actions"><button type="reset" class="btn btn-secondary">Limpiar</button><button class="btn btn-primary">${entry?'Registrar entrada':'Registrar salida'}</button></div></form></div>`;$('#movement-form').onsubmit=e=>saveMovement(e,type);}
async function saveMovement(e,type){e.preventDefault();const f=new FormData(e.target);const qty=Number(f.get('quantity')), item=state.items.find(i=>i.id===f.get('item_id'));if(!item)return;if(type==='EXIT'&&qty>Number(item.current_stock)){toast(`Stock insuficiente. Disponible: ${fmt(item.current_stock)} ${item.unit}`,true);return;}const payload={item_id:item.id,movement_type:type,quantity:qty,movement_date:new Date(f.get('movement_date')).toISOString(),notes:f.get('notes')||null};if(type==='ENTRY'){payload.supplier=f.get('supplier')||null;payload.document_number=f.get('document_number')||null}else{payload.destination=f.get('destination')||null;payload.responsible=f.get('responsible')||null}const {error}=await sb.from('movements').insert(payload);if(error){toast(error.message,true);return;}await loadData();renderView();toast(type==='ENTRY'?'Entrada registrada':'Salida registrada');}

function renderAlerts(){const alerts=state.items.filter(i=>i.stock_status!=='SUFFICIENT');$('#content').innerHTML=`<div class="panel"><div class="panel-head"><div><h2>Centro de reposición</h2><div class="sub">Artículos que necesitan atención inmediata.</div></div><span class="badge ${alerts.length?'critical':'ok'}">${alerts.length} pendientes</span></div><div class="alert-list">${alerts.length?alerts.map(i=>`<div class="alert-row ${i.stock_status==='CRITICAL'?'critical-row':'low-row'}"><div><b>${esc(i.code)} — ${esc(i.name)}</b><div class="alert-meta">${esc(i.category_name)} · Stock ${fmt(i.current_stock)} ${esc(i.unit)} · Mínimo ${fmt(i.minimum_stock)}</div></div><span class="badge ${statusClass(i.stock_status)}">${statusLabel(i.stock_status)}</span></div>`).join(''):`<div class="empty"><strong>Todo en orden</strong>No hay artículos por debajo de su stock mínimo.</div>`}</div></div>`;}
function renderMovements(){const rows=state.movements;$('#content').innerHTML=`<div class="panel"><div class="panel-head"><div><h2>Historial de movimientos</h2><div class="sub">Últimos ${rows.length} movimientos registrados.</div></div></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Código</th><th>Bien</th><th>Cantidad</th><th>Detalle</th></tr></thead><tbody>${rows.length?rows.map(m=>`<tr><td>${new Date(m.movement_date).toLocaleString('es-PE')}</td><td><span class="badge ${m.movement_type==='ENTRY'?'ok':'low'}">${m.movement_type==='ENTRY'?'ENTRADA':'SALIDA'}</span></td><td><b>${esc(m.items?.code||'')}</b></td><td>${esc(m.items?.name||'')}</td><td>${fmt(m.quantity)}</td><td>${esc(m.movement_type==='ENTRY'?(m.supplier||m.document_number||m.notes||'—'):(m.destination||m.responsible||m.notes||'—'))}</td></tr>`).join(''):`<tr><td colspan="6"><div class="empty"><strong>Sin movimientos</strong>Los registros aparecerán aquí.</div></td></tr>`}</tbody></table></div></div>`;}
function openModal(){$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function toast(msg,error=false){const t=$('#toast');if(!t)return;t.textContent=msg;t.className=`toast show ${error?'error':''}`;setTimeout(()=>t.className='toast',3500)}

init();
